# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'START.ui'
#
# Created: Thu Jul 28 17:53:40 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow_START(object):
    def setupUi(self, MainWindow_START):
        MainWindow_START.setObjectName(_fromUtf8("MainWindow_START"))
        MainWindow_START.resize(1062, 600)
        self.centralwidget = QtGui.QWidget(MainWindow_START)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 1061, 591))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_SHOW = QtGui.QWidget()
        self.tab_SHOW.setObjectName(_fromUtf8("tab_SHOW"))
        self.groupBox = QtGui.QGroupBox(self.tab_SHOW)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 541, 461))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_NAME = QtGui.QLabel(self.groupBox)
        self.label_NAME.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_NAME.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_NAME.setObjectName(_fromUtf8("label_NAME"))
        self.label_CLASS = QtGui.QLabel(self.groupBox)
        self.label_CLASS.setGeometry(QtCore.QRect(10, 80, 46, 13))
        self.label_CLASS.setObjectName(_fromUtf8("label_CLASS"))
        self.label_ROLL = QtGui.QLabel(self.groupBox)
        self.label_ROLL.setGeometry(QtCore.QRect(10, 130, 46, 13))
        self.label_ROLL.setObjectName(_fromUtf8("label_ROLL"))
        self.label_AYEAR = QtGui.QLabel(self.groupBox)
        self.label_AYEAR.setGeometry(QtCore.QRect(10, 180, 91, 16))
        self.label_AYEAR.setObjectName(_fromUtf8("label_AYEAR"))
        self.label_FATHER = QtGui.QLabel(self.groupBox)
        self.label_FATHER.setGeometry(QtCore.QRect(10, 230, 91, 16))
        self.label_FATHER.setObjectName(_fromUtf8("label_FATHER"))
        self.label_MOTHER = QtGui.QLabel(self.groupBox)
        self.label_MOTHER.setGeometry(QtCore.QRect(10, 280, 91, 16))
        self.label_MOTHER.setObjectName(_fromUtf8("label_MOTHER"))
        self.label_MOBILE = QtGui.QLabel(self.groupBox)
        self.label_MOBILE.setGeometry(QtCore.QRect(10, 330, 71, 16))
        self.label_MOBILE.setObjectName(_fromUtf8("label_MOBILE"))
        self.label_ADDRESS = QtGui.QLabel(self.groupBox)
        self.label_ADDRESS.setGeometry(QtCore.QRect(10, 400, 61, 16))
        self.label_ADDRESS.setObjectName(_fromUtf8("label_ADDRESS"))
        self.textBrowser_NAME = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser_NAME.setGeometry(QtCore.QRect(110, 20, 256, 31))
        self.textBrowser_NAME.setObjectName(_fromUtf8("textBrowser_NAME"))
        self.textBrowser_CLASS = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser_CLASS.setGeometry(QtCore.QRect(110, 70, 256, 31))
        self.textBrowser_CLASS.setObjectName(_fromUtf8("textBrowser_CLASS"))
        self.textBrowser_AYEAR = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser_AYEAR.setGeometry(QtCore.QRect(110, 170, 256, 31))
        self.textBrowser_AYEAR.setObjectName(_fromUtf8("textBrowser_AYEAR"))
        self.textBrowser_ROLL = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser_ROLL.setGeometry(QtCore.QRect(110, 120, 256, 31))
        self.textBrowser_ROLL.setObjectName(_fromUtf8("textBrowser_ROLL"))
        self.textBrowser_FATHER = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser_FATHER.setGeometry(QtCore.QRect(110, 220, 256, 31))
        self.textBrowser_FATHER.setObjectName(_fromUtf8("textBrowser_FATHER"))
        self.textBrowser_MOTHER = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser_MOTHER.setGeometry(QtCore.QRect(110, 270, 256, 31))
        self.textBrowser_MOTHER.setObjectName(_fromUtf8("textBrowser_MOTHER"))
        self.textBrowser_MOBILE = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser_MOBILE.setGeometry(QtCore.QRect(110, 320, 256, 31))
        self.textBrowser_MOBILE.setObjectName(_fromUtf8("textBrowser_MOBILE"))
        self.textBrowser_ADDRESS = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser_ADDRESS.setGeometry(QtCore.QRect(110, 370, 256, 81))
        self.textBrowser_ADDRESS.setObjectName(_fromUtf8("textBrowser_ADDRESS"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(380, 20, 151, 161))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_PHOTO = QtGui.QLabel(self.groupBox_5)
        self.label_PHOTO.setGeometry(QtCore.QRect(10, 20, 131, 131))
        self.label_PHOTO.setText(_fromUtf8(""))
        self.label_PHOTO.setObjectName(_fromUtf8("label_PHOTO"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_SHOW)
        self.groupBox_2.setGeometry(QtCore.QRect(550, 10, 501, 61))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_ID_1 = QtGui.QLabel(self.groupBox_2)
        self.label_ID_1.setGeometry(QtCore.QRect(60, 30, 61, 16))
        self.label_ID_1.setObjectName(_fromUtf8("label_ID_1"))
        self.pushButton_SUBMIT = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_SUBMIT.setGeometry(QtCore.QRect(280, 20, 81, 31))
        self.pushButton_SUBMIT.setObjectName(_fromUtf8("pushButton_SUBMIT"))
        self.lineEdit_ID_1 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_ID_1.setGeometry(QtCore.QRect(150, 30, 71, 21))
        self.lineEdit_ID_1.setObjectName(_fromUtf8("lineEdit_ID_1"))
        self.pushButton_RESET_1 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_RESET_1.setGeometry(QtCore.QRect(390, 20, 81, 31))
        self.pushButton_RESET_1.setObjectName(_fromUtf8("pushButton_RESET_1"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_SHOW)
        self.groupBox_3.setGeometry(QtCore.QRect(550, 80, 501, 471))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.tabWidget_2 = QtGui.QTabWidget(self.groupBox_3)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 20, 491, 451))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_FEES_2 = QtGui.QWidget()
        self.tab_FEES_2.setObjectName(_fromUtf8("tab_FEES_2"))
        self.tableWidget_FEES_2 = QtGui.QTableWidget(self.tab_FEES_2)
        self.tableWidget_FEES_2.setGeometry(QtCore.QRect(10, 10, 471, 411))
        self.tableWidget_FEES_2.setObjectName(_fromUtf8("tableWidget_FEES_2"))
        self.tableWidget_FEES_2.setColumnCount(3)
        self.tableWidget_FEES_2.setRowCount(12)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_FEES_2.setHorizontalHeaderItem(2, item)
        self.tabWidget_2.addTab(self.tab_FEES_2, _fromUtf8(""))
        self.tab_ATTENDENCE_2 = QtGui.QWidget()
        self.tab_ATTENDENCE_2.setObjectName(_fromUtf8("tab_ATTENDENCE_2"))
        self.tableWidget_ATTENDENCE_2 = QtGui.QTableWidget(self.tab_ATTENDENCE_2)
        self.tableWidget_ATTENDENCE_2.setGeometry(QtCore.QRect(10, 0, 471, 421))
        self.tableWidget_ATTENDENCE_2.setObjectName(_fromUtf8("tableWidget_ATTENDENCE_2"))
        self.tableWidget_ATTENDENCE_2.setColumnCount(2)
        self.tableWidget_ATTENDENCE_2.setRowCount(13)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_ATTENDENCE_2.setItem(12, 1, item)
        self.tabWidget_2.addTab(self.tab_ATTENDENCE_2, _fromUtf8(""))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_SHOW)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 480, 541, 71))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_STATUS_1 = QtGui.QLabel(self.groupBox_4)
        self.label_STATUS_1.setGeometry(QtCore.QRect(35, 30, 61, 20))
        self.label_STATUS_1.setObjectName(_fromUtf8("label_STATUS_1"))
        self.textBrowser_STATUS_1 = QtGui.QTextBrowser(self.groupBox_4)
        self.textBrowser_STATUS_1.setGeometry(QtCore.QRect(110, 20, 401, 31))
        self.textBrowser_STATUS_1.setObjectName(_fromUtf8("textBrowser_STATUS_1"))
        self.tabWidget.addTab(self.tab_SHOW, _fromUtf8(""))
        self.tab_NEW = QtGui.QWidget()
        self.tab_NEW.setObjectName(_fromUtf8("tab_NEW"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_NEW)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 561, 461))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_NAME_2 = QtGui.QLabel(self.groupBox_6)
        self.label_NAME_2.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.label_NAME_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_NAME_2.setObjectName(_fromUtf8("label_NAME_2"))
        self.label_CLASS_2 = QtGui.QLabel(self.groupBox_6)
        self.label_CLASS_2.setGeometry(QtCore.QRect(10, 90, 46, 13))
        self.label_CLASS_2.setObjectName(_fromUtf8("label_CLASS_2"))
        self.label_ROLL_2 = QtGui.QLabel(self.groupBox_6)
        self.label_ROLL_2.setGeometry(QtCore.QRect(10, 140, 46, 13))
        self.label_ROLL_2.setObjectName(_fromUtf8("label_ROLL_2"))
        self.label_AYEAR_2 = QtGui.QLabel(self.groupBox_6)
        self.label_AYEAR_2.setGeometry(QtCore.QRect(10, 190, 91, 16))
        self.label_AYEAR_2.setObjectName(_fromUtf8("label_AYEAR_2"))
        self.label_FATHER_2 = QtGui.QLabel(self.groupBox_6)
        self.label_FATHER_2.setGeometry(QtCore.QRect(10, 240, 91, 16))
        self.label_FATHER_2.setObjectName(_fromUtf8("label_FATHER_2"))
        self.label_MOTHER_2 = QtGui.QLabel(self.groupBox_6)
        self.label_MOTHER_2.setGeometry(QtCore.QRect(10, 290, 91, 16))
        self.label_MOTHER_2.setObjectName(_fromUtf8("label_MOTHER_2"))
        self.label_MOBILE_2 = QtGui.QLabel(self.groupBox_6)
        self.label_MOBILE_2.setGeometry(QtCore.QRect(10, 340, 71, 16))
        self.label_MOBILE_2.setObjectName(_fromUtf8("label_MOBILE_2"))
        self.label_ADDRESS_2 = QtGui.QLabel(self.groupBox_6)
        self.label_ADDRESS_2.setGeometry(QtCore.QRect(10, 400, 61, 16))
        self.label_ADDRESS_2.setObjectName(_fromUtf8("label_ADDRESS_2"))
        self.pushButton_SUBMIT_2 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_SUBMIT_2.setGeometry(QtCore.QRect(430, 190, 101, 51))
        self.pushButton_SUBMIT_2.setObjectName(_fromUtf8("pushButton_SUBMIT_2"))
        self.pushButton_RESET_2 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_RESET_2.setGeometry(QtCore.QRect(430, 250, 101, 51))
        self.pushButton_RESET_2.setObjectName(_fromUtf8("pushButton_RESET_2"))
        self.lineEdit_NAME_2 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_NAME_2.setGeometry(QtCore.QRect(140, 30, 251, 31))
        self.lineEdit_NAME_2.setObjectName(_fromUtf8("lineEdit_NAME_2"))
        self.lineEdit_CLASS_2 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_CLASS_2.setGeometry(QtCore.QRect(140, 80, 251, 31))
        self.lineEdit_CLASS_2.setObjectName(_fromUtf8("lineEdit_CLASS_2"))
        self.lineEdit_ROLL_2 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_ROLL_2.setGeometry(QtCore.QRect(140, 130, 251, 31))
        self.lineEdit_ROLL_2.setObjectName(_fromUtf8("lineEdit_ROLL_2"))
        self.lineEdit_AYEAR_2 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_AYEAR_2.setGeometry(QtCore.QRect(140, 180, 251, 31))
        self.lineEdit_AYEAR_2.setObjectName(_fromUtf8("lineEdit_AYEAR_2"))
        self.lineEdit_FATHER_2 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_FATHER_2.setGeometry(QtCore.QRect(140, 230, 251, 31))
        self.lineEdit_FATHER_2.setObjectName(_fromUtf8("lineEdit_FATHER_2"))
        self.lineEdit_MOTHER_2 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_MOTHER_2.setGeometry(QtCore.QRect(140, 280, 251, 31))
        self.lineEdit_MOTHER_2.setObjectName(_fromUtf8("lineEdit_MOTHER_2"))
        self.lineEdit_MOBILE_2 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_MOBILE_2.setGeometry(QtCore.QRect(140, 330, 251, 31))
        self.lineEdit_MOBILE_2.setObjectName(_fromUtf8("lineEdit_MOBILE_2"))
        self.textEdit_ADDRESS_2 = QtGui.QTextEdit(self.groupBox_6)
        self.textEdit_ADDRESS_2.setGeometry(QtCore.QRect(140, 380, 251, 71))
        self.textEdit_ADDRESS_2.setObjectName(_fromUtf8("textEdit_ADDRESS_2"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_NEW)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 490, 561, 61))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_STATUS_2 = QtGui.QLabel(self.groupBox_7)
        self.label_STATUS_2.setGeometry(QtCore.QRect(65, 30, 61, 20))
        self.label_STATUS_2.setObjectName(_fromUtf8("label_STATUS_2"))
        self.textBrowser_STATUS_2 = QtGui.QTextBrowser(self.groupBox_7)
        self.textBrowser_STATUS_2.setGeometry(QtCore.QRect(140, 20, 401, 31))
        self.textBrowser_STATUS_2.setObjectName(_fromUtf8("textBrowser_STATUS_2"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_NEW)
        self.groupBox_8.setGeometry(QtCore.QRect(580, 10, 471, 541))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.videoFrame = QtGui.QLabel(self.groupBox_8)
        self.videoFrame.setGeometry(QtCore.QRect(10, 20, 451, 351))
        self.videoFrame.setObjectName(_fromUtf8("videoFrame"))
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 420, 451, 80))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.pushButton_CAPTURE = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_CAPTURE.setGeometry(QtCore.QRect(110, 20, 91, 51))
        self.pushButton_CAPTURE.setObjectName(_fromUtf8("pushButton_CAPTURE"))
        self.pushButton_SHOWfromStream = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_SHOWfromStream.setGeometry(QtCore.QRect(240, 20, 91, 51))
        self.pushButton_SHOWfromStream.setObjectName(_fromUtf8("pushButton_SHOWfromStream"))
        self.tabWidget.addTab(self.tab_NEW, _fromUtf8(""))
        self.tab_FEE = QtGui.QWidget()
        self.tab_FEE.setObjectName(_fromUtf8("tab_FEE"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_FEE)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 10, 721, 41))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.label_FULLPAID_3 = QtGui.QLabel(self.groupBox_10)
        self.label_FULLPAID_3.setGeometry(QtCore.QRect(70, 20, 71, 16))
        self.label_FULLPAID_3.setObjectName(_fromUtf8("label_FULLPAID_3"))
        self.label_HALFPAID_3 = QtGui.QLabel(self.groupBox_10)
        self.label_HALFPAID_3.setGeometry(QtCore.QRect(260, 20, 121, 16))
        self.label_HALFPAID_3.setObjectName(_fromUtf8("label_HALFPAID_3"))
        self.label_NOTPAID_3 = QtGui.QLabel(self.groupBox_10)
        self.label_NOTPAID_3.setGeometry(QtCore.QRect(530, 20, 61, 16))
        self.label_NOTPAID_3.setObjectName(_fromUtf8("label_NOTPAID_3"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_FEE)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 60, 721, 71))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.label_MONTH_3 = QtGui.QLabel(self.groupBox_11)
        self.label_MONTH_3.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.label_MONTH_3.setObjectName(_fromUtf8("label_MONTH_3"))
        self.lineEdit_MONTH_3 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_MONTH_3.setGeometry(QtCore.QRect(100, 40, 113, 20))
        self.lineEdit_MONTH_3.setObjectName(_fromUtf8("lineEdit_MONTH_3"))
        self.label_OPTION_3 = QtGui.QLabel(self.groupBox_11)
        self.label_OPTION_3.setGeometry(QtCore.QRect(260, 40, 91, 16))
        self.label_OPTION_3.setObjectName(_fromUtf8("label_OPTION_3"))
        self.pushButton_SUBMIT_3 = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_SUBMIT_3.setGeometry(QtCore.QRect(500, 20, 81, 41))
        self.pushButton_SUBMIT_3.setObjectName(_fromUtf8("pushButton_SUBMIT_3"))
        self.pushButton_RESET_3 = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_RESET_3.setGeometry(QtCore.QRect(600, 20, 81, 41))
        self.pushButton_RESET_3.setObjectName(_fromUtf8("pushButton_RESET_3"))
        self.lineEdit_OPTION_3 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_OPTION_3.setGeometry(QtCore.QRect(350, 40, 91, 20))
        self.lineEdit_OPTION_3.setObjectName(_fromUtf8("lineEdit_OPTION_3"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_FEE)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 140, 721, 411))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.label_ID_3 = QtGui.QLabel(self.groupBox_12)
        self.label_ID_3.setGeometry(QtCore.QRect(20, 30, 21, 16))
        self.label_ID_3.setObjectName(_fromUtf8("label_ID_3"))
        self.label_NAME_3 = QtGui.QLabel(self.groupBox_12)
        self.label_NAME_3.setGeometry(QtCore.QRect(190, 30, 46, 13))
        self.label_NAME_3.setObjectName(_fromUtf8("label_NAME_3"))
        self.label_PAID_3 = QtGui.QLabel(self.groupBox_12)
        self.label_PAID_3.setGeometry(QtCore.QRect(70, 30, 31, 16))
        self.label_PAID_3.setObjectName(_fromUtf8("label_PAID_3"))
        self.label_DUE_4 = QtGui.QLabel(self.groupBox_12)
        self.label_DUE_4.setGeometry(QtCore.QRect(120, 30, 31, 16))
        self.label_DUE_4.setObjectName(_fromUtf8("label_DUE_4"))
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox_12)
        self.groupBox_13.setGeometry(QtCore.QRect(420, 50, 291, 271))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.label_TOTALSTUDENT_3 = QtGui.QLabel(self.groupBox_13)
        self.label_TOTALSTUDENT_3.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_TOTALSTUDENT_3.setObjectName(_fromUtf8("label_TOTALSTUDENT_3"))
        self.label_TOTALFEE_3 = QtGui.QLabel(self.groupBox_13)
        self.label_TOTALFEE_3.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_TOTALFEE_3.setObjectName(_fromUtf8("label_TOTALFEE_3"))
        self.label_COLLECTED_3 = QtGui.QLabel(self.groupBox_13)
        self.label_COLLECTED_3.setGeometry(QtCore.QRect(10, 180, 81, 16))
        self.label_COLLECTED_3.setObjectName(_fromUtf8("label_COLLECTED_3"))
        self.label_DUE_3 = QtGui.QLabel(self.groupBox_13)
        self.label_DUE_3.setGeometry(QtCore.QRect(10, 220, 61, 16))
        self.label_DUE_3.setObjectName(_fromUtf8("label_DUE_3"))
        self.textBrowser_TOTALSTUDENT_3 = QtGui.QTextBrowser(self.groupBox_13)
        self.textBrowser_TOTALSTUDENT_3.setGeometry(QtCore.QRect(170, 60, 81, 41))
        self.textBrowser_TOTALSTUDENT_3.setObjectName(_fromUtf8("textBrowser_TOTALSTUDENT_3"))
        self.textBrowser_TOTALFEE_3 = QtGui.QTextBrowser(self.groupBox_13)
        self.textBrowser_TOTALFEE_3.setGeometry(QtCore.QRect(170, 130, 81, 31))
        self.textBrowser_TOTALFEE_3.setObjectName(_fromUtf8("textBrowser_TOTALFEE_3"))
        self.textBrowser_COLLECTED_3 = QtGui.QTextBrowser(self.groupBox_13)
        self.textBrowser_COLLECTED_3.setGeometry(QtCore.QRect(170, 170, 81, 31))
        self.textBrowser_COLLECTED_3.setObjectName(_fromUtf8("textBrowser_COLLECTED_3"))
        self.textBrowser_DUE_3 = QtGui.QTextBrowser(self.groupBox_13)
        self.textBrowser_DUE_3.setGeometry(QtCore.QRect(170, 210, 81, 31))
        self.textBrowser_DUE_3.setObjectName(_fromUtf8("textBrowser_DUE_3"))
        self.groupBox_15 = QtGui.QGroupBox(self.groupBox_12)
        self.groupBox_15.setGeometry(QtCore.QRect(420, 340, 291, 61))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.label = QtGui.QLabel(self.groupBox_15)
        self.label.setGeometry(QtCore.QRect(5, 30, 61, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.textBrowser_STATUS_3 = QtGui.QTextBrowser(self.groupBox_15)
        self.textBrowser_STATUS_3.setGeometry(QtCore.QRect(70, 20, 211, 31))
        self.textBrowser_STATUS_3.setObjectName(_fromUtf8("textBrowser_STATUS_3"))
        self.textBrowser_OUTPUT_3 = QtGui.QTextBrowser(self.groupBox_12)
        self.textBrowser_OUTPUT_3.setGeometry(QtCore.QRect(10, 50, 401, 361))
        self.textBrowser_OUTPUT_3.setObjectName(_fromUtf8("textBrowser_OUTPUT_3"))
        self.groupBox_14 = QtGui.QGroupBox(self.tab_FEE)
        self.groupBox_14.setGeometry(QtCore.QRect(780, 10, 221, 541))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.label_MONTH_4 = QtGui.QLabel(self.groupBox_14)
        self.label_MONTH_4.setGeometry(QtCore.QRect(20, 30, 46, 13))
        self.label_MONTH_4.setObjectName(_fromUtf8("label_MONTH_4"))
        self.label_AMMOUNT_3 = QtGui.QLabel(self.groupBox_14)
        self.label_AMMOUNT_3.setGeometry(QtCore.QRect(120, 30, 61, 16))
        self.label_AMMOUNT_3.setObjectName(_fromUtf8("label_AMMOUNT_3"))
        self.label_NUR_3 = QtGui.QLabel(self.groupBox_14)
        self.label_NUR_3.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.label_NUR_3.setObjectName(_fromUtf8("label_NUR_3"))
        self.label_KG1_3 = QtGui.QLabel(self.groupBox_14)
        self.label_KG1_3.setGeometry(QtCore.QRect(10, 100, 51, 16))
        self.label_KG1_3.setObjectName(_fromUtf8("label_KG1_3"))
        self.label_KG2_3 = QtGui.QLabel(self.groupBox_14)
        self.label_KG2_3.setGeometry(QtCore.QRect(10, 130, 46, 13))
        self.label_KG2_3.setObjectName(_fromUtf8("label_KG2_3"))
        self.label_ONE_3 = QtGui.QLabel(self.groupBox_14)
        self.label_ONE_3.setGeometry(QtCore.QRect(10, 160, 46, 13))
        self.label_ONE_3.setObjectName(_fromUtf8("label_ONE_3"))
        self.label_TWO_3 = QtGui.QLabel(self.groupBox_14)
        self.label_TWO_3.setGeometry(QtCore.QRect(10, 190, 46, 13))
        self.label_TWO_3.setObjectName(_fromUtf8("label_TWO_3"))
        self.label_THREE_3 = QtGui.QLabel(self.groupBox_14)
        self.label_THREE_3.setGeometry(QtCore.QRect(10, 220, 46, 13))
        self.label_THREE_3.setObjectName(_fromUtf8("label_THREE_3"))
        self.label_FOUR_3 = QtGui.QLabel(self.groupBox_14)
        self.label_FOUR_3.setGeometry(QtCore.QRect(10, 250, 46, 13))
        self.label_FOUR_3.setObjectName(_fromUtf8("label_FOUR_3"))
        self.label_FIVE_3 = QtGui.QLabel(self.groupBox_14)
        self.label_FIVE_3.setGeometry(QtCore.QRect(10, 280, 46, 13))
        self.label_FIVE_3.setObjectName(_fromUtf8("label_FIVE_3"))
        self.label_SIX_3 = QtGui.QLabel(self.groupBox_14)
        self.label_SIX_3.setGeometry(QtCore.QRect(10, 310, 61, 16))
        self.label_SIX_3.setObjectName(_fromUtf8("label_SIX_3"))
        self.label_SEVEN_3 = QtGui.QLabel(self.groupBox_14)
        self.label_SEVEN_3.setGeometry(QtCore.QRect(10, 340, 61, 16))
        self.label_SEVEN_3.setObjectName(_fromUtf8("label_SEVEN_3"))
        self.label_EIGHT_3 = QtGui.QLabel(self.groupBox_14)
        self.label_EIGHT_3.setGeometry(QtCore.QRect(10, 370, 61, 16))
        self.label_EIGHT_3.setObjectName(_fromUtf8("label_EIGHT_3"))
        self.label_NINE_3 = QtGui.QLabel(self.groupBox_14)
        self.label_NINE_3.setGeometry(QtCore.QRect(10, 400, 71, 16))
        self.label_NINE_3.setObjectName(_fromUtf8("label_NINE_3"))
        self.lineEdit_NUR_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_NUR_3.setGeometry(QtCore.QRect(90, 70, 113, 20))
        self.lineEdit_NUR_3.setObjectName(_fromUtf8("lineEdit_NUR_3"))
        self.lineEdit_KG1_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_KG1_3.setGeometry(QtCore.QRect(90, 100, 113, 20))
        self.lineEdit_KG1_3.setObjectName(_fromUtf8("lineEdit_KG1_3"))
        self.lineEdit_KG2_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_KG2_3.setGeometry(QtCore.QRect(90, 130, 113, 20))
        self.lineEdit_KG2_3.setObjectName(_fromUtf8("lineEdit_KG2_3"))
        self.lineEdit_ONE_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_ONE_3.setGeometry(QtCore.QRect(90, 160, 113, 20))
        self.lineEdit_ONE_3.setObjectName(_fromUtf8("lineEdit_ONE_3"))
        self.lineEdit_TWO_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_TWO_3.setGeometry(QtCore.QRect(90, 190, 113, 20))
        self.lineEdit_TWO_3.setObjectName(_fromUtf8("lineEdit_TWO_3"))
        self.lineEdit_THREE_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_THREE_3.setGeometry(QtCore.QRect(90, 220, 113, 20))
        self.lineEdit_THREE_3.setObjectName(_fromUtf8("lineEdit_THREE_3"))
        self.lineEdit_FOUR_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_FOUR_3.setGeometry(QtCore.QRect(90, 250, 113, 20))
        self.lineEdit_FOUR_3.setObjectName(_fromUtf8("lineEdit_FOUR_3"))
        self.lineEdit_FIVE_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_FIVE_3.setGeometry(QtCore.QRect(90, 280, 113, 20))
        self.lineEdit_FIVE_3.setObjectName(_fromUtf8("lineEdit_FIVE_3"))
        self.lineEdit_SIX_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_SIX_3.setGeometry(QtCore.QRect(90, 310, 113, 20))
        self.lineEdit_SIX_3.setObjectName(_fromUtf8("lineEdit_SIX_3"))
        self.lineEdit_SEVEN_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_SEVEN_3.setGeometry(QtCore.QRect(90, 340, 113, 20))
        self.lineEdit_SEVEN_3.setObjectName(_fromUtf8("lineEdit_SEVEN_3"))
        self.lineEdit_EIGHT_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_EIGHT_3.setGeometry(QtCore.QRect(90, 370, 113, 20))
        self.lineEdit_EIGHT_3.setObjectName(_fromUtf8("lineEdit_EIGHT_3"))
        self.lineEdit_NINE_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_NINE_3.setGeometry(QtCore.QRect(90, 400, 113, 20))
        self.lineEdit_NINE_3.setObjectName(_fromUtf8("lineEdit_NINE_3"))
        self.pushButton_UPDATEFEE_3 = QtGui.QPushButton(self.groupBox_14)
        self.pushButton_UPDATEFEE_3.setGeometry(QtCore.QRect(50, 480, 131, 51))
        self.pushButton_UPDATEFEE_3.setObjectName(_fromUtf8("pushButton_UPDATEFEE_3"))
        self.label_TEN_3 = QtGui.QLabel(self.groupBox_14)
        self.label_TEN_3.setGeometry(QtCore.QRect(10, 430, 71, 16))
        self.label_TEN_3.setObjectName(_fromUtf8("label_TEN_3"))
        self.lineEdit_TEN_3 = QtGui.QLineEdit(self.groupBox_14)
        self.lineEdit_TEN_3.setGeometry(QtCore.QRect(90, 430, 113, 20))
        self.lineEdit_TEN_3.setObjectName(_fromUtf8("lineEdit_TEN_3"))
        self.tabWidget.addTab(self.tab_FEE, _fromUtf8(""))
        self.tab_SYBMITFEE = QtGui.QWidget()
        self.tab_SYBMITFEE.setObjectName(_fromUtf8("tab_SYBMITFEE"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab_SYBMITFEE)
        self.groupBox_16.setGeometry(QtCore.QRect(700, 150, 341, 231))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.label_TC_4 = QtGui.QLabel(self.groupBox_16)
        self.label_TC_4.setGeometry(QtCore.QRect(40, 100, 61, 16))
        self.label_TC_4.setObjectName(_fromUtf8("label_TC_4"))
        self.lineEdit_TC = QtGui.QLineEdit(self.groupBox_16)
        self.lineEdit_TC.setGeometry(QtCore.QRect(20, 140, 131, 20))
        self.lineEdit_TC.setObjectName(_fromUtf8("lineEdit_TC"))
        self.pushButton_UPDATEFEE_4 = QtGui.QPushButton(self.groupBox_16)
        self.pushButton_UPDATEFEE_4.setGeometry(QtCore.QRect(140, 510, 131, 31))
        self.pushButton_UPDATEFEE_4.setObjectName(_fromUtf8("pushButton_UPDATEFEE_4"))
        self.label_CA_4 = QtGui.QLabel(self.groupBox_16)
        self.label_CA_4.setGeometry(QtCore.QRect(190, 100, 81, 20))
        self.label_CA_4.setObjectName(_fromUtf8("label_CA_4"))
        self.lineEdit_CA = QtGui.QLineEdit(self.groupBox_16)
        self.lineEdit_CA.setGeometry(QtCore.QRect(170, 140, 141, 20))
        self.lineEdit_CA.setObjectName(_fromUtf8("lineEdit_CA"))
        self.label_ID_4 = QtGui.QLabel(self.groupBox_16)
        self.label_ID_4.setGeometry(QtCore.QRect(30, 40, 21, 16))
        self.label_ID_4.setObjectName(_fromUtf8("label_ID_4"))
        self.lineEdit_ID_40 = QtGui.QLineEdit(self.groupBox_16)
        self.lineEdit_ID_40.setGeometry(QtCore.QRect(60, 40, 71, 20))
        self.lineEdit_ID_40.setObjectName(_fromUtf8("lineEdit_ID_40"))
        self.label_MONTH_6 = QtGui.QLabel(self.groupBox_16)
        self.label_MONTH_6.setGeometry(QtCore.QRect(170, 40, 46, 13))
        self.label_MONTH_6.setObjectName(_fromUtf8("label_MONTH_6"))
        self.lineEdit_MONTH_40 = QtGui.QLineEdit(self.groupBox_16)
        self.lineEdit_MONTH_40.setGeometry(QtCore.QRect(220, 40, 71, 20))
        self.lineEdit_MONTH_40.setObjectName(_fromUtf8("lineEdit_MONTH_40"))
        self.pushButton_UPDATE_ATTAINDANCE = QtGui.QPushButton(self.groupBox_16)
        self.pushButton_UPDATE_ATTAINDANCE.setGeometry(QtCore.QRect(100, 180, 131, 31))
        self.pushButton_UPDATE_ATTAINDANCE.setObjectName(_fromUtf8("pushButton_UPDATE_ATTAINDANCE"))
        self.groupBox_17 = QtGui.QGroupBox(self.tab_SYBMITFEE)
        self.groupBox_17.setGeometry(QtCore.QRect(460, 10, 221, 541))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.label_MONTH_41 = QtGui.QLabel(self.groupBox_17)
        self.label_MONTH_41.setGeometry(QtCore.QRect(20, 30, 46, 13))
        self.label_MONTH_41.setObjectName(_fromUtf8("label_MONTH_41"))
        self.label_FEE_41 = QtGui.QLabel(self.groupBox_17)
        self.label_FEE_41.setGeometry(QtCore.QRect(120, 30, 61, 16))
        self.label_FEE_41.setObjectName(_fromUtf8("label_FEE_41"))
        self.label_KG1_41 = QtGui.QLabel(self.groupBox_17)
        self.label_KG1_41.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.label_KG1_41.setObjectName(_fromUtf8("label_KG1_41"))
        self.label_KG2_41 = QtGui.QLabel(self.groupBox_17)
        self.label_KG2_41.setGeometry(QtCore.QRect(10, 110, 51, 16))
        self.label_KG2_41.setObjectName(_fromUtf8("label_KG2_41"))
        self.label_ONE_41 = QtGui.QLabel(self.groupBox_17)
        self.label_ONE_41.setGeometry(QtCore.QRect(10, 150, 46, 13))
        self.label_ONE_41.setObjectName(_fromUtf8("label_ONE_41"))
        self.label_TWO_41 = QtGui.QLabel(self.groupBox_17)
        self.label_TWO_41.setGeometry(QtCore.QRect(10, 190, 46, 13))
        self.label_TWO_41.setObjectName(_fromUtf8("label_TWO_41"))
        self.label_THREE_41 = QtGui.QLabel(self.groupBox_17)
        self.label_THREE_41.setGeometry(QtCore.QRect(10, 230, 46, 13))
        self.label_THREE_41.setObjectName(_fromUtf8("label_THREE_41"))
        self.label_FOUR_41 = QtGui.QLabel(self.groupBox_17)
        self.label_FOUR_41.setGeometry(QtCore.QRect(10, 270, 46, 13))
        self.label_FOUR_41.setObjectName(_fromUtf8("label_FOUR_41"))
        self.label_FIVE_41 = QtGui.QLabel(self.groupBox_17)
        self.label_FIVE_41.setGeometry(QtCore.QRect(10, 310, 46, 13))
        self.label_FIVE_41.setObjectName(_fromUtf8("label_FIVE_41"))
        self.label_SIX_41 = QtGui.QLabel(self.groupBox_17)
        self.label_SIX_41.setGeometry(QtCore.QRect(10, 350, 46, 13))
        self.label_SIX_41.setObjectName(_fromUtf8("label_SIX_41"))
        self.label_SEVEN_41 = QtGui.QLabel(self.groupBox_17)
        self.label_SEVEN_41.setGeometry(QtCore.QRect(10, 390, 61, 16))
        self.label_SEVEN_41.setObjectName(_fromUtf8("label_SEVEN_41"))
        self.label_EIGHT_41 = QtGui.QLabel(self.groupBox_17)
        self.label_EIGHT_41.setGeometry(QtCore.QRect(10, 430, 61, 16))
        self.label_EIGHT_41.setObjectName(_fromUtf8("label_EIGHT_41"))
        self.label_NINE_41 = QtGui.QLabel(self.groupBox_17)
        self.label_NINE_41.setGeometry(QtCore.QRect(10, 470, 61, 16))
        self.label_NINE_41.setObjectName(_fromUtf8("label_NINE_41"))
        self.label_TEN_41 = QtGui.QLabel(self.groupBox_17)
        self.label_TEN_41.setGeometry(QtCore.QRect(10, 510, 71, 16))
        self.label_TEN_41.setObjectName(_fromUtf8("label_TEN_41"))
        self.textBrowser_KG1_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_KG1_41.setGeometry(QtCore.QRect(100, 60, 101, 31))
        self.textBrowser_KG1_41.setObjectName(_fromUtf8("textBrowser_KG1_41"))
        self.textBrowser_KG2_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_KG2_41.setGeometry(QtCore.QRect(100, 100, 101, 31))
        self.textBrowser_KG2_41.setObjectName(_fromUtf8("textBrowser_KG2_41"))
        self.textBrowser_ONE_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_ONE_41.setGeometry(QtCore.QRect(100, 140, 101, 31))
        self.textBrowser_ONE_41.setObjectName(_fromUtf8("textBrowser_ONE_41"))
        self.textBrowser_TWO_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_TWO_41.setGeometry(QtCore.QRect(100, 180, 101, 31))
        self.textBrowser_TWO_41.setObjectName(_fromUtf8("textBrowser_TWO_41"))
        self.textBrowser_THREE_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_THREE_41.setGeometry(QtCore.QRect(100, 220, 101, 31))
        self.textBrowser_THREE_41.setObjectName(_fromUtf8("textBrowser_THREE_41"))
        self.textBrowser_FOUR_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_FOUR_41.setGeometry(QtCore.QRect(100, 260, 101, 31))
        self.textBrowser_FOUR_41.setObjectName(_fromUtf8("textBrowser_FOUR_41"))
        self.textBrowser_FIVE_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_FIVE_41.setGeometry(QtCore.QRect(100, 300, 101, 31))
        self.textBrowser_FIVE_41.setObjectName(_fromUtf8("textBrowser_FIVE_41"))
        self.textBrowser_SIX_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_SIX_41.setGeometry(QtCore.QRect(100, 340, 101, 31))
        self.textBrowser_SIX_41.setObjectName(_fromUtf8("textBrowser_SIX_41"))
        self.textBrowser_SEVEN_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_SEVEN_41.setGeometry(QtCore.QRect(100, 380, 101, 31))
        self.textBrowser_SEVEN_41.setObjectName(_fromUtf8("textBrowser_SEVEN_41"))
        self.textBrowser_EIGHT_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_EIGHT_41.setGeometry(QtCore.QRect(100, 420, 101, 31))
        self.textBrowser_EIGHT_41.setObjectName(_fromUtf8("textBrowser_EIGHT_41"))
        self.textBrowser_NINE_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_NINE_41.setGeometry(QtCore.QRect(100, 460, 101, 31))
        self.textBrowser_NINE_41.setObjectName(_fromUtf8("textBrowser_NINE_41"))
        self.textBrowser_TEN_41 = QtGui.QTextBrowser(self.groupBox_17)
        self.textBrowser_TEN_41.setGeometry(QtCore.QRect(100, 500, 101, 31))
        self.textBrowser_TEN_41.setObjectName(_fromUtf8("textBrowser_TEN_41"))
        self.groupBox_18 = QtGui.QGroupBox(self.tab_SYBMITFEE)
        self.groupBox_18.setGeometry(QtCore.QRect(10, 10, 441, 211))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.label_ID_42 = QtGui.QLabel(self.groupBox_18)
        self.label_ID_42.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_ID_42.setObjectName(_fromUtf8("label_ID_42"))
        self.lineEdit_ID_42 = QtGui.QLineEdit(self.groupBox_18)
        self.lineEdit_ID_42.setGeometry(QtCore.QRect(90, 30, 113, 20))
        self.lineEdit_ID_42.setObjectName(_fromUtf8("lineEdit_ID_42"))
        self.label_MONTH_42 = QtGui.QLabel(self.groupBox_18)
        self.label_MONTH_42.setGeometry(QtCore.QRect(240, 30, 46, 13))
        self.label_MONTH_42.setObjectName(_fromUtf8("label_MONTH_42"))
        self.lineEdit_MONTH_42 = QtGui.QLineEdit(self.groupBox_18)
        self.lineEdit_MONTH_42.setGeometry(QtCore.QRect(290, 30, 113, 20))
        self.lineEdit_MONTH_42.setObjectName(_fromUtf8("lineEdit_MONTH_42"))
        self.pushButton_SUBMITFEE_42 = QtGui.QPushButton(self.groupBox_18)
        self.pushButton_SUBMITFEE_42.setGeometry(QtCore.QRect(180, 110, 91, 41))
        self.pushButton_SUBMITFEE_42.setObjectName(_fromUtf8("pushButton_SUBMITFEE_42"))
        self.label_FEEAMMOUNT_42 = QtGui.QLabel(self.groupBox_18)
        self.label_FEEAMMOUNT_42.setGeometry(QtCore.QRect(20, 80, 161, 16))
        self.label_FEEAMMOUNT_42.setObjectName(_fromUtf8("label_FEEAMMOUNT_42"))
        self.lineEdit_FEEAMMOUNT_42 = QtGui.QLineEdit(self.groupBox_18)
        self.lineEdit_FEEAMMOUNT_42.setGeometry(QtCore.QRect(180, 80, 91, 20))
        self.lineEdit_FEEAMMOUNT_42.setObjectName(_fromUtf8("lineEdit_FEEAMMOUNT_42"))
        self.pushButton_RESET_42 = QtGui.QPushButton(self.groupBox_18)
        self.pushButton_RESET_42.setGeometry(QtCore.QRect(180, 160, 91, 41))
        self.pushButton_RESET_42.setObjectName(_fromUtf8("pushButton_RESET_42"))
        self.groupBox_19 = QtGui.QGroupBox(self.tab_SYBMITFEE)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 240, 441, 181))
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.label_NAME_42 = QtGui.QLabel(self.groupBox_19)
        self.label_NAME_42.setGeometry(QtCore.QRect(70, 30, 46, 13))
        self.label_NAME_42.setObjectName(_fromUtf8("label_NAME_42"))
        self.label_CLASS_42 = QtGui.QLabel(self.groupBox_19)
        self.label_CLASS_42.setGeometry(QtCore.QRect(300, 30, 46, 13))
        self.label_CLASS_42.setObjectName(_fromUtf8("label_CLASS_42"))
        self.textBrowser_NAME_42 = QtGui.QTextBrowser(self.groupBox_19)
        self.textBrowser_NAME_42.setGeometry(QtCore.QRect(10, 60, 201, 31))
        self.textBrowser_NAME_42.setObjectName(_fromUtf8("textBrowser_NAME_42"))
        self.textBrowser_CLASS_42 = QtGui.QTextBrowser(self.groupBox_19)
        self.textBrowser_CLASS_42.setGeometry(QtCore.QRect(260, 60, 131, 31))
        self.textBrowser_CLASS_42.setObjectName(_fromUtf8("textBrowser_CLASS_42"))
        self.label_DUEFEE_4 = QtGui.QLabel(self.groupBox_19)
        self.label_DUEFEE_4.setGeometry(QtCore.QRect(230, 130, 51, 16))
        self.label_DUEFEE_4.setObjectName(_fromUtf8("label_DUEFEE_4"))
        self.textBrowser_DUEFEE_4 = QtGui.QTextBrowser(self.groupBox_19)
        self.textBrowser_DUEFEE_4.setGeometry(QtCore.QRect(290, 120, 71, 31))
        self.textBrowser_DUEFEE_4.setObjectName(_fromUtf8("textBrowser_DUEFEE_4"))
        self.label_PAIDFEE_4 = QtGui.QLabel(self.groupBox_19)
        self.label_PAIDFEE_4.setGeometry(QtCore.QRect(30, 130, 51, 20))
        self.label_PAIDFEE_4.setObjectName(_fromUtf8("label_PAIDFEE_4"))
        self.textBrowser_PAIDFEE_4 = QtGui.QTextBrowser(self.groupBox_19)
        self.textBrowser_PAIDFEE_4.setGeometry(QtCore.QRect(90, 120, 71, 31))
        self.textBrowser_PAIDFEE_4.setObjectName(_fromUtf8("textBrowser_PAIDFEE_4"))
        self.groupBox_20 = QtGui.QGroupBox(self.tab_SYBMITFEE)
        self.groupBox_20.setGeometry(QtCore.QRect(10, 440, 441, 81))
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.label_STATUS_42 = QtGui.QLabel(self.groupBox_20)
        self.label_STATUS_42.setGeometry(QtCore.QRect(5, 30, 61, 20))
        self.label_STATUS_42.setObjectName(_fromUtf8("label_STATUS_42"))
        self.textBrowser_STATUS_4 = QtGui.QTextBrowser(self.groupBox_20)
        self.textBrowser_STATUS_4.setGeometry(QtCore.QRect(80, 30, 351, 31))
        self.textBrowser_STATUS_4.setObjectName(_fromUtf8("textBrowser_STATUS_4"))
        self.tabWidget.addTab(self.tab_SYBMITFEE, _fromUtf8(""))
        self.tab_SENDMESSAGE = QtGui.QWidget()
        self.tab_SENDMESSAGE.setObjectName(_fromUtf8("tab_SENDMESSAGE"))
        self.groupBox_21 = QtGui.QGroupBox(self.tab_SENDMESSAGE)
        self.groupBox_21.setGeometry(QtCore.QRect(0, 10, 681, 541))
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.groupBox_25 = QtGui.QGroupBox(self.groupBox_21)
        self.groupBox_25.setGeometry(QtCore.QRect(10, 30, 331, 341))
        self.groupBox_25.setObjectName(_fromUtf8("groupBox_25"))
        self.textBrowser_B_5 = QtGui.QTextBrowser(self.groupBox_25)
        self.textBrowser_B_5.setGeometry(QtCore.QRect(10, 20, 311, 311))
        self.textBrowser_B_5.setObjectName(_fromUtf8("textBrowser_B_5"))
        self.groupBox_26 = QtGui.QGroupBox(self.groupBox_21)
        self.groupBox_26.setGeometry(QtCore.QRect(10, 380, 331, 151))
        self.groupBox_26.setObjectName(_fromUtf8("groupBox_26"))
        self.label_7 = QtGui.QLabel(self.groupBox_26)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.textEdit_B_MESSAGE_5 = QtGui.QTextEdit(self.groupBox_26)
        self.textEdit_B_MESSAGE_5.setGeometry(QtCore.QRect(70, 30, 251, 111))
        self.textEdit_B_MESSAGE_5.setObjectName(_fromUtf8("textEdit_B_MESSAGE_5"))
        self.groupBox_27 = QtGui.QGroupBox(self.groupBox_21)
        self.groupBox_27.setGeometry(QtCore.QRect(350, 380, 321, 151))
        self.groupBox_27.setObjectName(_fromUtf8("groupBox_27"))
        self.label_8 = QtGui.QLabel(self.groupBox_27)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_27)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_B_USERNAME_5 = QtGui.QLineEdit(self.groupBox_27)
        self.lineEdit_B_USERNAME_5.setGeometry(QtCore.QRect(80, 30, 161, 20))
        self.lineEdit_B_USERNAME_5.setObjectName(_fromUtf8("lineEdit_B_USERNAME_5"))
        self.lineEdit_B_PASSWORD_5 = QtGui.QLineEdit(self.groupBox_27)
        self.lineEdit_B_PASSWORD_5.setGeometry(QtCore.QRect(80, 60, 161, 20))
        self.lineEdit_B_PASSWORD_5.setObjectName(_fromUtf8("lineEdit_B_PASSWORD_5"))
        self.pushButton_B_SENDMESSAGE_5 = QtGui.QPushButton(self.groupBox_27)
        self.pushButton_B_SENDMESSAGE_5.setGeometry(QtCore.QRect(80, 90, 91, 23))
        self.pushButton_B_SENDMESSAGE_5.setObjectName(_fromUtf8("pushButton_B_SENDMESSAGE_5"))
        self.pushButton_B_CLEAR_5 = QtGui.QPushButton(self.groupBox_27)
        self.pushButton_B_CLEAR_5.setGeometry(QtCore.QRect(180, 90, 61, 23))
        self.pushButton_B_CLEAR_5.setObjectName(_fromUtf8("pushButton_B_CLEAR_5"))
        self.groupBox_28 = QtGui.QGroupBox(self.groupBox_21)
        self.groupBox_28.setGeometry(QtCore.QRect(350, 30, 321, 171))
        self.groupBox_28.setObjectName(_fromUtf8("groupBox_28"))
        self.label_10 = QtGui.QLabel(self.groupBox_28)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 46, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_B_MONTH_5 = QtGui.QLineEdit(self.groupBox_28)
        self.lineEdit_B_MONTH_5.setGeometry(QtCore.QRect(60, 30, 113, 20))
        self.lineEdit_B_MONTH_5.setObjectName(_fromUtf8("lineEdit_B_MONTH_5"))
        self.pushButton_B_CHECKRESULT_5 = QtGui.QPushButton(self.groupBox_28)
        self.pushButton_B_CHECKRESULT_5.setGeometry(QtCore.QRect(210, 30, 81, 23))
        self.pushButton_B_CHECKRESULT_5.setObjectName(_fromUtf8("pushButton_B_CHECKRESULT_5"))
        self.label_11 = QtGui.QLabel(self.groupBox_28)
        self.label_11.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_B_SENDFROM_5 = QtGui.QLineEdit(self.groupBox_28)
        self.lineEdit_B_SENDFROM_5.setGeometry(QtCore.QRect(80, 90, 71, 20))
        self.lineEdit_B_SENDFROM_5.setObjectName(_fromUtf8("lineEdit_B_SENDFROM_5"))
        self.label_12 = QtGui.QLabel(self.groupBox_28)
        self.label_12.setGeometry(QtCore.QRect(160, 90, 21, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_B_TO_5 = QtGui.QLineEdit(self.groupBox_28)
        self.lineEdit_B_TO_5.setGeometry(QtCore.QRect(190, 90, 71, 20))
        self.lineEdit_B_TO_5.setObjectName(_fromUtf8("lineEdit_B_TO_5"))
        self.pushButton_B_SUBMIT_5 = QtGui.QPushButton(self.groupBox_28)
        self.pushButton_B_SUBMIT_5.setGeometry(QtCore.QRect(120, 130, 75, 23))
        self.pushButton_B_SUBMIT_5.setObjectName(_fromUtf8("pushButton_B_SUBMIT_5"))
        self.groupBox_29 = QtGui.QGroupBox(self.groupBox_21)
        self.groupBox_29.setGeometry(QtCore.QRect(350, 210, 321, 161))
        self.groupBox_29.setObjectName(_fromUtf8("groupBox_29"))
        self.checkBox_B_5 = QtGui.QCheckBox(self.groupBox_29)
        self.checkBox_B_5.setGeometry(QtCore.QRect(30, 40, 70, 17))
        self.checkBox_B_5.setObjectName(_fromUtf8("checkBox_B_5"))
        self.pushButton_B1_CHECKRESULT_5 = QtGui.QPushButton(self.groupBox_29)
        self.pushButton_B1_CHECKRESULT_5.setGeometry(QtCore.QRect(140, 40, 81, 23))
        self.pushButton_B1_CHECKRESULT_5.setObjectName(_fromUtf8("pushButton_B1_CHECKRESULT_5"))
        self.label_13 = QtGui.QLabel(self.groupBox_29)
        self.label_13.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_B1_SENDFROM_5 = QtGui.QLineEdit(self.groupBox_29)
        self.lineEdit_B1_SENDFROM_5.setGeometry(QtCore.QRect(80, 90, 71, 20))
        self.lineEdit_B1_SENDFROM_5.setObjectName(_fromUtf8("lineEdit_B1_SENDFROM_5"))
        self.lineEdit_B1_TO_5 = QtGui.QLineEdit(self.groupBox_29)
        self.lineEdit_B1_TO_5.setGeometry(QtCore.QRect(190, 90, 71, 20))
        self.lineEdit_B1_TO_5.setObjectName(_fromUtf8("lineEdit_B1_TO_5"))
        self.label_14 = QtGui.QLabel(self.groupBox_29)
        self.label_14.setGeometry(QtCore.QRect(160, 90, 21, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.pushButton_B1_SUBMIT_5 = QtGui.QPushButton(self.groupBox_29)
        self.pushButton_B1_SUBMIT_5.setGeometry(QtCore.QRect(120, 130, 75, 23))
        self.pushButton_B1_SUBMIT_5.setObjectName(_fromUtf8("pushButton_B1_SUBMIT_5"))
        self.groupBox_22 = QtGui.QGroupBox(self.tab_SENDMESSAGE)
        self.groupBox_22.setGeometry(QtCore.QRect(690, 10, 361, 541))
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.label_2 = QtGui.QLabel(self.groupBox_22)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 21, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_S_ID_5 = QtGui.QLineEdit(self.groupBox_22)
        self.lineEdit_S_ID_5.setGeometry(QtCore.QRect(40, 30, 61, 20))
        self.lineEdit_S_ID_5.setObjectName(_fromUtf8("lineEdit_S_ID_5"))
        self.label_3 = QtGui.QLabel(self.groupBox_22)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 41, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_S_NAME_5 = QtGui.QLineEdit(self.groupBox_22)
        self.lineEdit_S_NAME_5.setGeometry(QtCore.QRect(160, 30, 191, 20))
        self.lineEdit_S_NAME_5.setObjectName(_fromUtf8("lineEdit_S_NAME_5"))
        self.groupBox_23 = QtGui.QGroupBox(self.groupBox_22)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 100, 341, 171))
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.textBrowser_S_5 = QtGui.QTextBrowser(self.groupBox_23)
        self.textBrowser_S_5.setGeometry(QtCore.QRect(10, 20, 321, 141))
        self.textBrowser_S_5.setObjectName(_fromUtf8("textBrowser_S_5"))
        self.pushButton_S_SUBMIT_5 = QtGui.QPushButton(self.groupBox_22)
        self.pushButton_S_SUBMIT_5.setGeometry(QtCore.QRect(100, 70, 75, 23))
        self.pushButton_S_SUBMIT_5.setObjectName(_fromUtf8("pushButton_S_SUBMIT_5"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_22)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 70, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_22)
        self.label_4.setGeometry(QtCore.QRect(70, 290, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_S_NUMBER_5 = QtGui.QLineEdit(self.groupBox_22)
        self.lineEdit_S_NUMBER_5.setGeometry(QtCore.QRect(130, 290, 201, 20))
        self.lineEdit_S_NUMBER_5.setObjectName(_fromUtf8("lineEdit_S_NUMBER_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_22)
        self.label_5.setGeometry(QtCore.QRect(70, 350, 51, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.textEdit_S_MESSAGE_5 = QtGui.QTextEdit(self.groupBox_22)
        self.textEdit_S_MESSAGE_5.setGeometry(QtCore.QRect(130, 330, 201, 91))
        self.textEdit_S_MESSAGE_5.setObjectName(_fromUtf8("textEdit_S_MESSAGE_5"))
        self.pushButton_S_SENDMESSAGE_5 = QtGui.QPushButton(self.groupBox_22)
        self.pushButton_S_SENDMESSAGE_5.setGeometry(QtCore.QRect(180, 430, 91, 23))
        self.pushButton_S_SENDMESSAGE_5.setObjectName(_fromUtf8("pushButton_S_SENDMESSAGE_5"))
        self.groupBox_24 = QtGui.QGroupBox(self.groupBox_22)
        self.groupBox_24.setGeometry(QtCore.QRect(10, 460, 341, 71))
        self.groupBox_24.setObjectName(_fromUtf8("groupBox_24"))
        self.textBrowser_S_STATUS_5 = QtGui.QTextBrowser(self.groupBox_24)
        self.textBrowser_S_STATUS_5.setGeometry(QtCore.QRect(110, 20, 221, 31))
        self.textBrowser_S_STATUS_5.setObjectName(_fromUtf8("textBrowser_S_STATUS_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_24)
        self.label_6.setGeometry(QtCore.QRect(50, 30, 51, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.tabWidget.addTab(self.tab_SENDMESSAGE, _fromUtf8(""))
        self.pushButton_SENDMESSAGE = QtGui.QPushButton(self.centralwidget)
        self.pushButton_SENDMESSAGE.setGeometry(QtCore.QRect(880, 10, 111, 23))
        self.pushButton_SENDMESSAGE.setObjectName(_fromUtf8("pushButton_SENDMESSAGE"))
        MainWindow_START.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_START)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_START)

    def retranslateUi(self, MainWindow_START):
        MainWindow_START.setWindowTitle(_translate("MainWindow_START", "School-DBMS", None))
        self.groupBox.setTitle(_translate("MainWindow_START", "Student Details", None))
        self.label_NAME.setText(_translate("MainWindow_START", "Name :", None))
        self.label_CLASS.setText(_translate("MainWindow_START", "Class :", None))
        self.label_ROLL.setText(_translate("MainWindow_START", "Roll No :", None))
        self.label_AYEAR.setText(_translate("MainWindow_START", "Addmission Year :", None))
        self.label_FATHER.setText(_translate("MainWindow_START", "Father\'s Name :", None))
        self.label_MOTHER.setText(_translate("MainWindow_START", "Mothers\'s Name :", None))
        self.label_MOBILE.setText(_translate("MainWindow_START", "Mobile No:", None))
        self.label_ADDRESS.setText(_translate("MainWindow_START", "Address :", None))
        self.groupBox_5.setTitle(_translate("MainWindow_START", "Photo", None))
        self.groupBox_2.setTitle(_translate("MainWindow_START", "User-Input", None))
        self.label_ID_1.setText(_translate("MainWindow_START", "ID Number :", None))
        self.pushButton_SUBMIT.setText(_translate("MainWindow_START", "SUBMIT", None))
        self.pushButton_RESET_1.setText(_translate("MainWindow_START", "RESET", None))
        self.groupBox_3.setTitle(_translate("MainWindow_START", "Details", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow_START", "January", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow_START", "Febuary", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow_START", "March", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow_START", "April", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow_START", "May", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow_START", "June", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow_START", "July", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow_START", "August", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow_START", "September", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow_START", "October", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow_START", "November", None))
        item = self.tableWidget_FEES_2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow_START", "December", None))
        item = self.tableWidget_FEES_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_START", "Total Fee", None))
        item = self.tableWidget_FEES_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_START", "Paid Fee", None))
        item = self.tableWidget_FEES_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_START", "Due Fee", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_FEES_2), _translate("MainWindow_START", "Fees", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow_START", "January", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow_START", "February", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow_START", "March", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow_START", "April", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow_START", "May", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow_START", "June", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow_START", "July", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow_START", "August", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow_START", "September", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow_START", "October", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow_START", "November", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow_START", "December", None))
        item = self.tableWidget_ATTENDENCE_2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow_START", "Total", None))
        item = self.tableWidget_ATTENDENCE_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_START", "Class Attainded", None))
        item = self.tableWidget_ATTENDENCE_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_START", "Total Class", None))
        __sortingEnabled = self.tableWidget_ATTENDENCE_2.isSortingEnabled()
        self.tableWidget_ATTENDENCE_2.setSortingEnabled(False)
        item = self.tableWidget_ATTENDENCE_2.item(0, 0)
        item.setText(_translate("MainWindow_START", "20", None))
        item = self.tableWidget_ATTENDENCE_2.item(0, 1)
        item.setText(_translate("MainWindow_START", "25", None))
        item = self.tableWidget_ATTENDENCE_2.item(1, 0)
        item.setText(_translate("MainWindow_START", "18", None))
        item = self.tableWidget_ATTENDENCE_2.item(1, 1)
        item.setText(_translate("MainWindow_START", "22", None))
        item = self.tableWidget_ATTENDENCE_2.item(2, 0)
        item.setText(_translate("MainWindow_START", "21", None))
        item = self.tableWidget_ATTENDENCE_2.item(2, 1)
        item.setText(_translate("MainWindow_START", "27", None))
        item = self.tableWidget_ATTENDENCE_2.item(3, 0)
        item.setText(_translate("MainWindow_START", "24", None))
        item = self.tableWidget_ATTENDENCE_2.item(3, 1)
        item.setText(_translate("MainWindow_START", "25", None))
        item = self.tableWidget_ATTENDENCE_2.item(4, 0)
        item.setText(_translate("MainWindow_START", "18", None))
        item = self.tableWidget_ATTENDENCE_2.item(4, 1)
        item.setText(_translate("MainWindow_START", "21", None))
        item = self.tableWidget_ATTENDENCE_2.item(5, 0)
        item.setText(_translate("MainWindow_START", "15", None))
        item = self.tableWidget_ATTENDENCE_2.item(5, 1)
        item.setText(_translate("MainWindow_START", "20", None))
        item = self.tableWidget_ATTENDENCE_2.item(6, 0)
        item.setText(_translate("MainWindow_START", "19", None))
        item = self.tableWidget_ATTENDENCE_2.item(6, 1)
        item.setText(_translate("MainWindow_START", "28", None))
        item = self.tableWidget_ATTENDENCE_2.item(7, 0)
        item.setText(_translate("MainWindow_START", "21", None))
        item = self.tableWidget_ATTENDENCE_2.item(7, 1)
        item.setText(_translate("MainWindow_START", "26", None))
        item = self.tableWidget_ATTENDENCE_2.item(8, 0)
        item.setText(_translate("MainWindow_START", "17", None))
        item = self.tableWidget_ATTENDENCE_2.item(8, 1)
        item.setText(_translate("MainWindow_START", "27", None))
        item = self.tableWidget_ATTENDENCE_2.item(9, 0)
        item.setText(_translate("MainWindow_START", "25", None))
        item = self.tableWidget_ATTENDENCE_2.item(9, 1)
        item.setText(_translate("MainWindow_START", "29", None))
        item = self.tableWidget_ATTENDENCE_2.item(10, 0)
        item.setText(_translate("MainWindow_START", "12", None))
        item = self.tableWidget_ATTENDENCE_2.item(10, 1)
        item.setText(_translate("MainWindow_START", "21", None))
        item = self.tableWidget_ATTENDENCE_2.item(11, 0)
        item.setText(_translate("MainWindow_START", "22", None))
        item = self.tableWidget_ATTENDENCE_2.item(11, 1)
        item.setText(_translate("MainWindow_START", "25", None))
        item = self.tableWidget_ATTENDENCE_2.item(12, 0)
        item.setText(_translate("MainWindow_START", "200", None))
        item = self.tableWidget_ATTENDENCE_2.item(12, 1)
        item.setText(_translate("MainWindow_START", "230", None))
        self.tableWidget_ATTENDENCE_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_ATTENDENCE_2), _translate("MainWindow_START", "Attendence", None))
        self.groupBox_4.setTitle(_translate("MainWindow_START", "Output", None))
        self.label_STATUS_1.setText(_translate("MainWindow_START", "<html><head/><body><p><span style=\" font-size:10pt; color:#00007f;\">STATUS :</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SHOW), _translate("MainWindow_START", "Show-Details", None))
        self.groupBox_6.setTitle(_translate("MainWindow_START", "Fill Details", None))
        self.label_NAME_2.setText(_translate("MainWindow_START", "Name :", None))
        self.label_CLASS_2.setText(_translate("MainWindow_START", "Class :", None))
        self.label_ROLL_2.setText(_translate("MainWindow_START", "Roll No :", None))
        self.label_AYEAR_2.setText(_translate("MainWindow_START", "Addmission Year :", None))
        self.label_FATHER_2.setText(_translate("MainWindow_START", "Father\'s Name :", None))
        self.label_MOTHER_2.setText(_translate("MainWindow_START", "Mothers\'s Name :", None))
        self.label_MOBILE_2.setText(_translate("MainWindow_START", "Mobile No:", None))
        self.label_ADDRESS_2.setText(_translate("MainWindow_START", "Address :", None))
        self.pushButton_SUBMIT_2.setText(_translate("MainWindow_START", "SUBMIT", None))
        self.pushButton_RESET_2.setText(_translate("MainWindow_START", "RESET", None))
        self.groupBox_7.setTitle(_translate("MainWindow_START", "Output", None))
        self.label_STATUS_2.setText(_translate("MainWindow_START", "<html><head/><body><p><span style=\" font-size:10pt; color:#00007f;\">STATUS :</span></p></body></html>", None))
        self.groupBox_8.setTitle(_translate("MainWindow_START", "Display", None))
        self.videoFrame.setText(_translate("MainWindow_START", "Feed Label", None))
        self.groupBox_9.setTitle(_translate("MainWindow_START", "Controls", None))
        self.pushButton_CAPTURE.setText(_translate("MainWindow_START", "CAPTURE", None))
        self.pushButton_SHOWfromStream.setText(_translate("MainWindow_START", "VIEW", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_NEW), _translate("MainWindow_START", "New-Details", None))
        self.groupBox_10.setTitle(_translate("MainWindow_START", "Option", None))
        self.label_FULLPAID_3.setText(_translate("MainWindow_START", "<html><head/><body><p><span style=\" font-size:9pt; color:#00007f;\">1.Full Paid</span></p></body></html>", None))
        self.label_HALFPAID_3.setText(_translate("MainWindow_START", "<html><head/><body><p><span style=\" font-size:9pt; color:#00007f;\">2.Paid But have Dues</span></p></body></html>", None))
        self.label_NOTPAID_3.setText(_translate("MainWindow_START", "<html><head/><body><p><span style=\" font-size:9pt; color:#00007f;\">3.Not Paid</span></p></body></html>", None))
        self.groupBox_11.setTitle(_translate("MainWindow_START", "User Input", None))
        self.label_MONTH_3.setText(_translate("MainWindow_START", "Select Month :", None))
        self.label_OPTION_3.setText(_translate("MainWindow_START", "Select An Option :", None))
        self.pushButton_SUBMIT_3.setText(_translate("MainWindow_START", "SUBMIT", None))
        self.pushButton_RESET_3.setText(_translate("MainWindow_START", "RESET", None))
        self.groupBox_12.setTitle(_translate("MainWindow_START", "Fee Details", None))
        self.label_ID_3.setText(_translate("MainWindow_START", "<html><head/><body><p><span style=\" font-weight:600; color:#005500;\">ID</span></p></body></html>", None))
        self.label_NAME_3.setText(_translate("MainWindow_START", "<html><head/><body><p><span style=\" font-weight:600; color:#005500;\">Name</span></p></body></html>", None))
        self.label_PAID_3.setText(_translate("MainWindow_START", "<html><head/><body><p><span style=\" font-weight:600; color:#005500;\">Paid </span></p></body></html>", None))
        self.label_DUE_4.setText(_translate("MainWindow_START", "<html><head/><body><p><span style=\" font-weight:600; color:#005500;\">Due </span></p></body></html>", None))
        self.groupBox_13.setTitle(_translate("MainWindow_START", "Output", None))
        self.label_TOTALSTUDENT_3.setText(_translate("MainWindow_START", "Total Student\'s Found :", None))
        self.label_TOTALFEE_3.setText(_translate("MainWindow_START", "Total Fee of this Month : ", None))
        self.label_COLLECTED_3.setText(_translate("MainWindow_START", "Fee Collected :", None))
        self.label_DUE_3.setText(_translate("MainWindow_START", "Due Fee :", None))
        self.groupBox_15.setTitle(_translate("MainWindow_START", "Output", None))
        self.label.setText(_translate("MainWindow_START", "<html><head/><body><p><span style=\" font-size:10pt; color:#00007f;\">STATUS :</span></p></body></html>", None))
        self.groupBox_14.setTitle(_translate("MainWindow_START", "Update Fee", None))
        self.label_MONTH_4.setText(_translate("MainWindow_START", "Month", None))
        self.label_AMMOUNT_3.setText(_translate("MainWindow_START", "Fee Amount", None))
        self.label_NUR_3.setText(_translate("MainWindow_START", "Nur :", None))
        self.label_KG1_3.setText(_translate("MainWindow_START", "KG-1 :", None))
        self.label_KG2_3.setText(_translate("MainWindow_START", "KG-2 :", None))
        self.label_ONE_3.setText(_translate("MainWindow_START", "One :", None))
        self.label_TWO_3.setText(_translate("MainWindow_START", "Two :", None))
        self.label_THREE_3.setText(_translate("MainWindow_START", "Three :", None))
        self.label_FOUR_3.setText(_translate("MainWindow_START", "Four :", None))
        self.label_FIVE_3.setText(_translate("MainWindow_START", "Five :", None))
        self.label_SIX_3.setText(_translate("MainWindow_START", "Six :", None))
        self.label_SEVEN_3.setText(_translate("MainWindow_START", "Seven :", None))
        self.label_EIGHT_3.setText(_translate("MainWindow_START", "Eight :", None))
        self.label_NINE_3.setText(_translate("MainWindow_START", "Nine :", None))
        self.pushButton_UPDATEFEE_3.setText(_translate("MainWindow_START", "UPDATE FEE", None))
        self.label_TEN_3.setText(_translate("MainWindow_START", "Ten :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_FEE), _translate("MainWindow_START", "Fee-Details", None))
        self.groupBox_16.setTitle(_translate("MainWindow_START", "Update Attendance", None))
        self.label_TC_4.setText(_translate("MainWindow_START", "Total Class", None))
        self.pushButton_UPDATEFEE_4.setText(_translate("MainWindow_START", "UPDATE ATTENDENCE", None))
        self.label_CA_4.setText(_translate("MainWindow_START", "Cass Attaineded", None))
        self.label_ID_4.setText(_translate("MainWindow_START", "ID :", None))
        self.label_MONTH_6.setText(_translate("MainWindow_START", "Month :", None))
        self.pushButton_UPDATE_ATTAINDANCE.setText(_translate("MainWindow_START", "UPDATE ATTAINDANCE", None))
        self.groupBox_17.setTitle(_translate("MainWindow_START", "Fee Structure", None))
        self.label_MONTH_41.setText(_translate("MainWindow_START", "Month", None))
        self.label_FEE_41.setText(_translate("MainWindow_START", "Fee", None))
        self.label_KG1_41.setText(_translate("MainWindow_START", "KG-1 :", None))
        self.label_KG2_41.setText(_translate("MainWindow_START", "KG-2 :", None))
        self.label_ONE_41.setText(_translate("MainWindow_START", "One :", None))
        self.label_TWO_41.setText(_translate("MainWindow_START", "Two :", None))
        self.label_THREE_41.setText(_translate("MainWindow_START", "Three :", None))
        self.label_FOUR_41.setText(_translate("MainWindow_START", "Four :", None))
        self.label_FIVE_41.setText(_translate("MainWindow_START", "Five :", None))
        self.label_SIX_41.setText(_translate("MainWindow_START", "Six :", None))
        self.label_SEVEN_41.setText(_translate("MainWindow_START", "Seven :", None))
        self.label_EIGHT_41.setText(_translate("MainWindow_START", "Eight :", None))
        self.label_NINE_41.setText(_translate("MainWindow_START", "Nine :", None))
        self.label_TEN_41.setText(_translate("MainWindow_START", "Ten :", None))
        self.groupBox_18.setTitle(_translate("MainWindow_START", "User Input", None))
        self.label_ID_42.setText(_translate("MainWindow_START", "ID Number :", None))
        self.label_MONTH_42.setText(_translate("MainWindow_START", "Month :", None))
        self.pushButton_SUBMITFEE_42.setText(_translate("MainWindow_START", "SUBMIT FEE", None))
        self.label_FEEAMMOUNT_42.setText(_translate("MainWindow_START", "Enter Amount to be Submitted :", None))
        self.pushButton_RESET_42.setText(_translate("MainWindow_START", "RESET", None))
        self.groupBox_19.setTitle(_translate("MainWindow_START", "Details", None))
        self.label_NAME_42.setText(_translate("MainWindow_START", "Name", None))
        self.label_CLASS_42.setText(_translate("MainWindow_START", "Class", None))
        self.label_DUEFEE_4.setText(_translate("MainWindow_START", "Due Fee :", None))
        self.label_PAIDFEE_4.setText(_translate("MainWindow_START", "Paid Fee :", None))
        self.groupBox_20.setTitle(_translate("MainWindow_START", "Output", None))
        self.label_STATUS_42.setText(_translate("MainWindow_START", "<html><head/><body><p><span style=\" font-size:10pt; color:#00007f;\">STATUS :</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SYBMITFEE), _translate("MainWindow_START", "Submit-Fee/Attaindance", None))
        self.groupBox_21.setTitle(_translate("MainWindow_START", "Bulk-Message", None))
        self.groupBox_25.setTitle(_translate("MainWindow_START", "Display", None))
        self.groupBox_26.setTitle(_translate("MainWindow_START", "Message", None))
        self.label_7.setText(_translate("MainWindow_START", "Message :", None))
        self.groupBox_27.setTitle(_translate("MainWindow_START", "Send Message", None))
        self.label_8.setText(_translate("MainWindow_START", "Username :", None))
        self.label_9.setText(_translate("MainWindow_START", "Password :", None))
        self.pushButton_B_SENDMESSAGE_5.setText(_translate("MainWindow_START", "SEND MESSAGE", None))
        self.pushButton_B_CLEAR_5.setText(_translate("MainWindow_START", "CLEAR", None))
        self.groupBox_28.setTitle(_translate("MainWindow_START", "Due Fee", None))
        self.label_10.setText(_translate("MainWindow_START", "Month :", None))
        self.pushButton_B_CHECKRESULT_5.setText(_translate("MainWindow_START", "Check Result", None))
        self.label_11.setText(_translate("MainWindow_START", "Send From :", None))
        self.label_12.setText(_translate("MainWindow_START", "To :", None))
        self.pushButton_B_SUBMIT_5.setText(_translate("MainWindow_START", "SUBMIT", None))
        self.groupBox_29.setTitle(_translate("MainWindow_START", "Send To All", None))
        self.checkBox_B_5.setText(_translate("MainWindow_START", "Send To All", None))
        self.pushButton_B1_CHECKRESULT_5.setText(_translate("MainWindow_START", "Check Result", None))
        self.label_13.setText(_translate("MainWindow_START", "Send From :", None))
        self.label_14.setText(_translate("MainWindow_START", "To :", None))
        self.pushButton_B1_SUBMIT_5.setText(_translate("MainWindow_START", "SUBMIT", None))
        self.groupBox_22.setTitle(_translate("MainWindow_START", "Single-Message ", None))
        self.label_2.setText(_translate("MainWindow_START", "ID :", None))
        self.label_3.setText(_translate("MainWindow_START", "Name :", None))
        self.groupBox_23.setTitle(_translate("MainWindow_START", "Result", None))
        self.pushButton_S_SUBMIT_5.setText(_translate("MainWindow_START", "SUBMIT", None))
        self.pushButton_2.setText(_translate("MainWindow_START", "RESET", None))
        self.label_4.setText(_translate("MainWindow_START", "Number :", None))
        self.label_5.setText(_translate("MainWindow_START", "Message :", None))
        self.pushButton_S_SENDMESSAGE_5.setText(_translate("MainWindow_START", " SEND MESSAGE", None))
        self.groupBox_24.setTitle(_translate("MainWindow_START", "Output", None))
        self.label_6.setText(_translate("MainWindow_START", "STATUS :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SENDMESSAGE), _translate("MainWindow_START", "Message", None))
        self.pushButton_SENDMESSAGE.setText(_translate("MainWindow_START", "Send Message", None))

